kind: Template
apiVersion: v1
metadata:
  name: masu-template
  annotations:
    openshift.io/display-name: "Masu"
    description: "Data ingestion engine for Koku"
    tags: "python,flask"
    iconClass: "icon-python"
    openshift.io/long-description: "This template defines resources needed to run the Masu application, including a build configuration and an application deployment configuration."
    openshift.io/provider-display-name: "Red Hat, Inc."
    openshift.io/documentation-url: "https://koku.readthedocs.io/en/latest/"
labels:
  app: masu
  template: masu-template
objects:
- kind: Service
  apiVersion: v1
  metadata:
    annotations:
      description: Exposes flower
    name: ${NAME}-flower
    labels:
      app: ${NAME}
  spec:
    ports:
    - name: 5555-tcp
      port: 5555
      protocol: TCP
      targetPort: 5555
    selector:
      name: ${NAME}-flower
- kind: Route
  apiVersion: v1
  metadata:
    name: ${NAME}-flower
    labels:
      app: ${NAME}
  spec:
    host: ${APPLICATION_DOMAIN}
    to:
      kind: Service
      name: ${NAME}-flower
- kind: BuildConfig
  apiVersion: v1
  metadata:
    annotations:
      description: Defines how to build the application
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}-flower
    labels:
      app: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}-flower:latest
    resources:
      limits:
        memory: ${BUILD_MEMORY_LIMIT}
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        env:
          - name: PIP_INDEX_URL
            value: ${PIP_INDEX_URL}
          - name: PIPENV_PYPI_MIRROR
            value: ${PIPENV_PYPI_MIRROR}
          - name: ENABLE_PIPENV
            value: "true"
          - name: APP_CONFIG
            valueFrom:
              configMapKeyRef:
                name: ${NAME}
                key: app-config
                optional: false
          - name: APP_HOME
            valueFrom:
              configMapKeyRef:
                name: ${NAME}
                key: app-home
          - name: APP_MODULE
            valueFrom:
              configMapKeyRef:
                name: ${NAME}
                key: app-module
        from:
          kind: ImageStreamTag
          name: python-36-centos7:latest
          namespace: ${NAMESPACE}
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    annotations:
      description: Defines how to deploy the celery monitoring app
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}-flower
    labels:
      app: ${NAME}
  spec:
    replicas: 1
    selector:
      name: ${NAME}-flower
    resources:
      limits:
        cpu: ${CELERY_FLOWER_CPU_LIMIT}
        memory: ${CELERY_FLOWER_MEMORY_LIMIT}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${NAME}-flower
        name: ${NAME}-flower
      spec:
        containers:
        - name: ${NAME}-flower
          image: ${NAME}-flower
          command:
            - /bin/bash
            - -c
            - >
              PYTHONPATH=. scl enable rh-python36 --
              flower -A masu.celery.worker
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: ${DATABASE_SERVICE_NAME}
                  optional: false
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: ${DATABASE_SERVICE_NAME}
                  optional: false
            - name: MASU_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: masu-secret-key
                  name: ${NAME}
                  optional: false
            - name: DATABASE_ENGINE
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}
                  key: database-engine
                  optional: false
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}
                  key: database-name
                  optional: false
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}
                  key: postgres-sql-service-host
                  optional: false
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}
                  key: postgres-sql-service-port
                  optional: false
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}
                  key: rabbitmq-host
                  optional: false
          livenessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 5555
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 5555
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 10
          resources:
            limits:
              cpu: ${CELERY_FLOWER_CPU_LIMIT}
              memory: ${CELERY_FLOWER_MEMORY_LIMIT}
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - ${NAME}-flower
        from:
          kind: ImageStreamTag
          name: ${NAME}-flower:latest
      type: ImageChange
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${NAME}-flower
    annotations:
      description: "Keeps track of changes in the application image"
    labels:
      app: ${NAME}
parameters:
- description: The name assigned to all frontend objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: masu
- description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  name: NAMESPACE
  required: true
  value: myproject
- description: Maximum amount of memory the Flower container can use.
  displayName: Memory Limit
  name: CELERY_FLOWER_MEMORY_LIMIT
  required: true
  value: 1Gi
- description: Maximum amount of CPU the Flower container can use.
  displayName: CPU Limit
  name: CELERY_FLOWER_CPU_LIMIT
  required: true
  value: '1'
- description: Maximum amount of memory the build container can use.
  displayName: Build Memory Limit
  name: BUILD_MEMORY_LIMIT
  required: true
  value: 1Gi
- description: The custom PyPi index URL
  displayName: Custom PyPi Index URL
  name: PIP_INDEX_URL
- description: The custom PipEnv PyPi index URL
  displayName: Custom PipEnv PyPi Index URL
  name: PIPENV_PYPI_MIRROR
- description: Github trigger secret.  A difficult to guess string encoded as part
    of the webhook URL.  Not encrypted.
  displayName: GitHub Webhook Secret
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: GITHUB_WEBHOOK_SECRET
- displayName: Database Service Name
  name: DATABASE_SERVICE_NAME
  required: true
  value: koku-pgsql
- description: The URL of the repository with your application source code.
  displayName: Git Repository URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/project-koku/masu.git
- description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch.
  displayName: Git Reference
  name: SOURCE_REPOSITORY_REF
- description: Set this to the relative path to your project if it is not in the root
    of your repository.
  displayName: Context Directory
  name: CONTEXT_DIR
- description: The exposed hostname that will route to the app service, if left
    blank a value will be defaulted.
  displayName: Application Hostname
  name: APPLICATION_DOMAIN
