apiVersion: v1
kind: Template
labels:
  template: rabbitmq
metadata:
  annotations:
    description: RabbitMQ Deployment and Runtime Components
    iconClass: icon-erlang
    tags: erlang,rabbitmq
  creationTimestamp: null
  name: rabbitmq
objects:
- apiVersion: v1
  kind: RoleBinding
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: view
  roleRef:
    name: view
  subjects:
  - kind: ServiceAccount
    name: default
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    clusterIP: None
    ports:
    - name: 4369-tcp
      port: 4369
      protocol: TCP
      targetPort: 4369
    - name: 5671-tcp
      port: 5671
      protocol: TCP
      targetPort: 5671
    - name: 5672-tcp
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: 25672-tcp
      port: 25672
      protocol: TCP
      targetPort: 25672
    selector:
      application: ${APPLICATION_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 3
    selector:
      matchLabels:
        application: ${APPLICATION_NAME}
    serviceName: ${APPLICATION_NAME}
    template:
      metadata:
        labels:
          application: ${APPLICATION_NAME}
      spec:
        containers:
        - env:
          - name: AUTOCLUSTER_DELAY
            value: "10"
          - name: AUTOCLUSTER_TYPE
            value: k8s
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: RABBITMQ_ERLANG_COOKIE
            value: ${RABBITMQ_ERLANG_COOKIE}
          - name: RABBITMQ_NODENAME
            value: rabbit@$(MY_POD_IP)
          - name: RABBITMQ_USE_LONGNAME
            value: "true"
          image: ${APPLICATION_NAME}:${RABBITMQ_VERSION}
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 25672
            protocol: TCP
          - containerPort: 4369
            protocol: TCP
          - containerPort: 5671
            protocol: TCP
          - containerPort: 5672
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/rabbitmq/mnesia
            name: mnesia
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 10
    volumeClaimTemplates:
    - metadata:
        name: mnesia
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      application: rabbitmq
    name: rabbitmq
  spec:
    lookupPolicy:
      local: true
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: rabbitmq:${RABBITMQ_VERSION}
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      dockerStrategy:
        env:
        - name: ERLANG_VERSION
          value: ${ERLANG_VERSION}
        - name: RABBITMQ_AUTOCLUSTER_VERSION
          value: ${RABBITMQ_AUTOCLUSTER_VERSION}
        - name: RABBITMQ_VERSION
          value: ${RABBITMQ_VERSION}
        forcePull: true
        from:
          kind: ImageStreamTag
          name: ${FROM_IMAGE}
      type: Docker
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: rhel
  spec:
    dockerImageRepository: registry.access.redhat.com/rhel7/rhel
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: registry.access.redhat.com/rhel7/rhel:7.3
      importPolicy: {}
      name: "7.3"
      referencePolicy:
        type: Source
    - annotations: null
      from:
        kind: DockerImage
        name: registry.access.redhat.com/rhel7/rhel:7.4
      importPolicy: {}
      name: "7.4"
      referencePolicy:
        type: Source
    - annotations: null
      from:
        kind: DockerImage
        name: registry.access.redhat.com/rhel7/rhel:latest
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: rabbitmq
- description: RabbitMQ version to build
  name: RABBITMQ_VERSION
  required: true
  value: 3.7.5
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: rabbitmq
- description: Path within Git repository to build; empty for root of repository
  name: CONTEXT_DIR
  value: openshift/rabbitmq
- description: Erlang version to use
  name: ERLANG_VERSION
  required: true
  value: "20.3.4"
- description: Image stream tag for the image you'd like to use to build the application
  name: FROM_IMAGE
  required: true
  value: rhel:7.4
- description: RabbitMQ Autocluster version to use
  name: RABBITMQ_AUTOCLUSTER_VERSION
  required: true
  value: 0.10.0
- description: RabbitMQ version to build
  name: RABBITMQ_VERSION
  required: true
  value: 3.6.15
- description: Git branch/tag reference
  name: SOURCE_REPOSITORY_REF
  value: master
- description: Git source URL for application
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/project-koku/masu
- description: RabbitMQ Erlang Cookie
  name: RABBITMQ_ERLANG_COOKIE
  from: '[a-zA-Z0-9]{16}'
  generate: expression
