kind: Template
apiVersion: v1
metadata:
  name: masu-template
  annotations:
    openshift.io/display-name: "Masu"
    description: "Data ingestion engine for Koku"
    tags: "python,flask"
    iconClass: "icon-python"
    openshift.io/long-description: "This template defines resources needed to run the Masu application, including a build configuration and an application deployment configuration."
    openshift.io/provider-display-name: "Red Hat, Inc."
    openshift.io/documentation-url: "https://koku.readthedocs.io/en/latest/"
labels:
  app: masu
  template: masu-template
objects:
- kind: Secret
  apiVersion: v1
  metadata:
    labels:
      app: ${NAME}
      template: ${NAME}-template
    annotations:
      template.openshift.io/expose-secret-key: "{.data['masu-secret-key']}"
    name: ${NAME}
  stringData:
    masu-secret-key: ${MASU_SECRET_KEY}
    aws-access-key-id: ${AWS_ACCESS_KEY_ID}
    aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
parameters:
- description: The name assigned to all frontend objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: masu
- description: Set this to a long random string.
  displayName: Application Secret Key
  from: '[a-zA-Z0-9]{50}'
  generate: expression
  name: MASU_SECRET_KEY
- displayName: AWS Access Key ID
  from: ${AWS_ACCESS_KEY_ID}
  name: AWS_ACCESS_KEY_ID
- displayName: AWS Secret Access Key
  from: ${AWS_SECRET_ACCESS_KEY}
  name: AWS_SECRET_ACCESS_KEY
